<?php
function forena_schools_menu() {
	$items['assessments'] = array(
	  'type' => MENU_NORMAL_ITEM,
	  'title' => t('Assessments'),
	  'access callback' => 'forena_schools_access',
	  'access arguments' => array('teacher'),
	  'page callback' => 'forena_schools_assessments',
	  'file' => 'inc/common.inc',
	);

	$items['flex'] = array(
	  'type' => MENU_CALLBACK,
	  'access callback' => TRUE,
	  'page callback' => 'forena_schools_flex',
	  'file' => 'inc/common.inc',
	);

	$items['flexpopup'] = array(
	  'type' => MENU_CALLBACK,
	  'access callback' => TRUE,
	  'page callback' => 'forena_schools_flex',
	  'page arguments' => array(1, TRUE),
	);

	$items['flexServices'] = array(
	  'type' => MENU_CALLBACK,
	  'access callback' => TRUE,
	  'page callback' => 'forena_schools_data',
	  'file' => 'inc/common.inc',
	);

	return $items;
}

function forena_schools_theme() {
  return array( 'forena_schools_flex_popup' => array(
      'variables' => array('item' => NULL, 'feed' => 0),
    ),
  );
}

function forena_schools_access($security) {
	require_once 'inc/common.inc';
	return ForenaSchools::instance()->access($security);
}

/**
 *
 * Enter description here ...
 * @param unknown_type $app
 */
function forena_schools_assessments($app='') {
	$args = func_get_args();
	$app = implode('/', $args);
  $m_path = drupal_get_path('module', 'forena_schools');
	$flexfile = $m_path . '/flex/'.$app . '.swf';

	drupal_add_js($m_path . '/flex/swfobject.js');
  $fs = ForenaSchools::instance();
	if (!$app)  {
		if ($fs->access('dist_admin')) {
			$app = 'DistrictDashboard';
		}
		elseif ($fs->access('bldg_admin')) {
			$app = 'BuidingDashboard';
		}
		elseif ($fs->access('teacher')) {
			$app = 'TeacherDashboard';
		}
		else {
			drupal_access_denied();
		}
	}
  if (file_exists($flexfile)) {
  	$output = forena_schools_flex($app);
  }
  else {
		$output = forena_report($app);
  }
  return $output;
}

function forena_schools_connection_string() {
	global $databases;
	$db = $databases['default']['default'];
	$db_name = $db['database'];
	$user_name = $db['username'];
	$password = $db['password'];
	$host = $db['host'];
	$port = $db['port'];
	$uri = "dbname=$db_name user=$user_name password=$password";
	if ($port) $uri .= " port=$port";
	return $uri;
}

function forena_schools_forena_repos_alter(&$repos) {
	$m_path = drupal_get_path('module', 'forena_schools');
	$repos['ims'] = array(
	  'path' => $m_path . '/data_blocks',
	  'title' => 'Forena Schools',
		'uri' => forena_schools_connection_string(),
	  'data provider' => 'FrxPostgres',
	  'debug' => @$_GET['debug']|| @$_GET['appdebug'],
	  'postgres_xml' => TRUE,
	  'access callback' => 'user_access',
	  'user callback' => 'forena_schools_current_login',
	  'search path' => 'public,import',
  );

  $repos['menus'] = array(
    'path' => $m_path . '/menus',
    'title' => 'Forena Schools Menus',
    'uri' => "file://$m_path/menus",
    'data provider' => 'FrxFiles',
    'access callback' => 'user_access',
  );

}



function forena_schools_current_login() {
	require_once('inc/ForenaSchools.inc');
	$o =  ForenaSchools::instance();
	$user = $o->user;
	return @$user['login'];
}

function forena_schools_render_partial($template,$vars='',$extract=true) {
	$m_path = drupal_get_path('module', 'forena_schools');
  if (is_array($vars) && $extract==true)  {
    extract($vars);
  }
  ob_start();
  include($m_path . "/" . $template.".tpl.php");
  $output = ob_get_contents();
  ob_end_clean();
  return $output;
}

function forena_schools_service($service) {
	$object = null;
	require_once 'inc/ForenaSchools.inc';
	$include_file = drupal_get_path('module', 'forena_schools') . "/services/$service.data.php";
	if (file_exists($include_file)) {
		require_once $include_file;
		if (class_exists($service)) {
			$object = new $service;
		}
	}
	return $object;
}

/**
 * Renders a flex applciation in a popup window without theme
 * @param unknown_type $a
 */
function forena_schools_flex($application, $popup=false) {
  global $base_url;
  $vars = array();
  if (@$_GET['popup']) $popup = TRUE;
  $service = forena_schools_service($application);
  if (!$service) {
  	drupal_not_found();
  }
  else {
  	$vars['title'] = $service->title;
  }
  $m_path = drupal_get_path('module', 'forena_schools');
  $js = array();
  $js[] = $m_path .  '/flex/swfobject.js';
  $js[] = $m_path .  '/inc/pedaflex.js';
  $fvar = $_GET;
  $fvar['dataService'] =  $base_url . '/flexServices';
  $fvar['basePath'] = rtrim($base_url,'/');
  $base_path = $GLOBALS['base_path'];
  $flexPath = "flex/";
  if (@$_GET['debug']=='true') {
  	$flexPath = "bin-debug/";
  }
  $vars['flexPath'] = $flexPath;
  unset($fvar['q']);
  $flashfile = $m_path . '/' . $flexPath . $application . '.swf';
  $vars['flashfile'] = $base_path . $flashfile . '?d=' . filemtime($flashfile);
  $vars['application'] = $application;
  $vars['div_id'] = $application. '_div';
  $vars['flashvars'] = http_build_query($fvar);
  $vars['flashvars_json'] = json_encode($fvar, JSON_FORCE_OBJECT);
  if ($popup) $vars['height']='100%'; else $vars['height']='85%';
  $output = forena_schools_render_partial('flex',$vars);
  if ($popup) {
    $variables= array('content' => $output, 'js' => $js, 'title' =>$vars['title']);
  	$output = theme('forena_schools_flex_popup', $variables);
  	print $output;
  }
  else {
  	foreach ($js as $j) {
     drupal_add_js($j);
  	}
    return $output;
  }
}

function theme_forena_schools_flex_popup($variables) {
	$js = '';
	if (isset($variables['js'])) foreach($variables['js'] as $j) {
		$js .= "\n".'  <script src="' . base_path() . $j . '" language="javascript" type="text/javascript"></script>';
	}
	$variables['scripts'] = $js;
	print forena_schools_render_partial('popup', $variables);
}

function forena_schools_forena_controls() {
	$controls = array();
	$controls[] = array(
    'file' => 'inc/FrxPedagoggleScores.inc',
    'class' => 'FrxPedagoggleScores',
  );
  return $controls;
}

function forena_schools_forena_report_directory() {
	return drupal_get_path('module', 'forena_schools') . '/reports';
}

/**
 * Data service for flex applications.
 */
function forena_schools_data() {
  // Determine if the include file is in the path.
	$class = $_REQUEST['service'];
	$method = $_REQUEST['method'];
	$m_path = drupal_get_path('module', 'forena_schools');
	$class_file = $m_path . '/services/'.$class.'.data.php';
  $data_debug = @$_GET['debug'] || @$_GET['appdebug'];
	// Only load the file if the file name exists
	if (file_exists($class_file)) {
	  include_once($class_file);
	  if(class_exists($class)) {
	  	$handler = new $class;
	  }
	  else {
	    $handler = new DataBroker();
	  }
	  $auth = true;
	  if (method_exists($handler,'auth')) {
	  	$auth = call_user_func(array($handler,'auth'));
	  }
	  if ($auth) {
		  if (method_exists($handler,$method)) {
		    //header('Content-type: text/xml');
		    $data = call_user_func(array($handler,$method));
		    if ($data_debug==true && $class!='LogViewer') {
		    	watchdog('Data '. $class . '.' . $method, htmlspecialchars(print_r($_REQUEST,1)). "\n" . htmlspecialchars($data));
		    }
		    print $data;
		  }
		  else {
		    watchdog('error', 'Method Not Found',print_r($_REQUEST,1));
		    print "<pre>$method: Method Not Found</pre>";
		  }
	  } else {
	  	watchdog('error', 'Data Service Access Denied',"Service: $class \n Method:$method \n User: \n" . print_r(current_user(),1));
	  	print "<pre>Access Denied</pre>";
	  }
	}
	else {
	    watchdog('debug Data Service',  'Data Service  Not Found',print_r($_REQUEST,1));
		print "<pre>$class: Service Not Found</pre>";
	}
  drupal_get_messages();
}

/**
 * Implementation of hook_perm
 *
 * @return unknown
 */
function forena_schools_permission() {
  $perms = array(
    'administer forena schools' => array('title' => t('Administer Forena Schools')),
    'manage profiles' => array('title' => t('Administer Forena Reports')),
    'manage assessments' => array('title' => t('Define Assessments')),
    'import assessments' => array('title' => t('Import Assessments')),
    );
  return $perms;
}


