<?php
require_once 'ForenaSchools.inc';
require_once 'ForenaSchoolsAssessment.inc';
require_once 'ForenaSchoolsYear.inc';
require_once 'ForenaSchoolsValidation.inc';
require_once 'ForenaSchoolsPerson.inc';
require_once 'ForenaSchoolsStudent.inc';
require_once 'ForenaSchoolsGroup.inc';
require_once 'ForenaSchoolsTest.inc';
// Trying the following to get around line ending problems.
ini_set('auto_detect_line_endings',true);
