<?php
// $Id: forena.common.inc,v 1.4.2.25 2011/02/12 20:48:27 metzlerd Exp $
/**
 * @file
 * Common functions used throughout the project but loaded in this
 * file to keep the module file lean.
 */
// Include Report renderer.
require_once('FrxReport.inc');
require_once('FrxDataProvider.inc');
require_once('FrxPedagoggle.inc');
require_once('FrxReportGenerator.inc');
require_once('FrxSQLQueryBuilder.inc');
require_once('FrxData.inc');
